import { Item } from './types';

export const ITEMS: Record<string, Item> = {
  sword_normal: {
    id: 'sword_normal',
    name: 'Normal Sword',
    type: 'weapon',
    icon: '/res/objects/sword_normal.png',
    description: '[Normal Sword]\nAn old sword, but still sharp enough for combat.',
    attackValue: 1,
    price: 20,
    motion1: 5,
    motion2: 25,
  },
  axe: {
    id: 'axe',
    name: 'Woodcutter Axe',
    type: 'weapon',
    icon: '/res/objects/axe.png',
    description: '[Woodcutter Axe]\nA bit heavy, but can chop down dry trees!',
    attackValue: 2,
    price: 75,
    motion1: 20,
    motion2: 40,
  },
  pickaxe: {
    id: 'pickaxe',
    name: 'Pickaxe',
    type: 'weapon',
    icon: '/res/objects/pickaxe.png',
    description: '[Pickaxe]\nCan break cracked and destructible stone walls.',
    attackValue: 2,
    price: 75,
    motion1: 10,
    motion2: 20,
  },
  shield_wood: {
    id: 'shield_wood',
    name: 'Wood Shield',
    type: 'shield',
    icon: '/res/objects/shield_wood.png',
    description: '[Wood Shield]\nA simple wooden shield made by village carpenters.',
    defenseValue: 1,
    price: 35,
  },
  shield_blue: {
    id: 'shield_blue',
    name: 'Blue Shield',
    type: 'shield',
    icon: '/res/objects/shield_blue.png',
    description: '[Blue Shield]\nA sturdy iron shield imbued with azure protection.',
    defenseValue: 2,
    price: 250,
  },
  potion_red: {
    id: 'potion_red',
    name: 'Red Potion',
    type: 'consumable',
    icon: '/res/objects/potion_red.png',
    description: '[Red Potion]\nHeals your wounds and recovers 5 HP.',
    healValue: 5,
    price: 25,
    amount: 1,
  },
  key: {
    id: 'key',
    name: 'Key',
    type: 'key',
    icon: '/res/objects/key.png',
    description: '[Key]\nOpens locked wooden and iron dungeon doors.',
    price: 100,
    amount: 1,
  },
  lantern: {
    id: 'lantern',
    name: 'Lantern',
    type: 'tool',
    icon: '/res/objects/lantern.png',
    description: '[Lantern]\nIlluminates dark caves, dungeons, and night pathways.',
    price: 80,
  },
  tent: {
    id: 'tent',
    name: 'Tent',
    type: 'consumable',
    icon: '/res/objects/tent.png',
    description: '[Tent]\nSleep and rest to recover all HP and Mana.',
    price: 150,
    amount: 1,
  },
  blue_heart: {
    id: 'blue_heart',
    name: 'Blue Gem',
    type: 'quest',
    icon: '/res/objects/blueheart.png',
    description: '[Blue Gem]\nThe legendary relic of ancient power! Victory!',
    price: 9999,
  },
};

export function createItem(key: string, amount = 1): Item {
  const base = ITEMS[key] || ITEMS.sword_normal;
  return { ...base, amount };
}
